import Head from "next/head";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Container } from "@chakra-ui/react";

export default function Layout({ children, metaTitle, metaDescription }) {
  return (
    <>
      <Head>
        <title> {`Humanation - ${metaTitle}`} </title>{" "}
        <meta
          name="description"
          content={metaDescription || "Generated by create next app"}
        />{" "}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>{" "}
      <Container maxW="xl" color="white">
        <div className="border border-stone-500 min-h-screen">
          <Header />
          {children}
        </div>
      </Container>
    </>
  );
}
